apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-i-universe-xyz
  version: "1.19"
  region: "us-east-1"
  tags:
    Project: kekdao
    Environent: dev

vpc:
  cidr: 10.107.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]

secretsEncryption:
  keyARN: "arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        Resource: '*'
  - metadata:
      name: external-dns
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "route53:ChangeResourceRecordSets"
        Resource: 'arn:aws:route53:::hostedzone/*'
      - Effect: Allow
        Action:
        - "route53:ListHostedZones"
        - "route53:ListResourceRecordSets"
        Resource: '*'
  - metadata:
      name: kustomize-controller
      namespace: flux-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "kms:Encrypt"
        - "kms:Decrypt"
        - "kms:ReEncrypt*"
        - "kms:GenerateDataKey*"
        - "kms:DescribeKey"
        Resource:
        - "arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "kekDAO"
      repository: "kek-infrastructure-eks-base"
      personal: "false"
      branch: "main"
      namespace: "flux-system"
      path: "clusters/dev.i.universe.xyz"

managedNodeGroups:
  # - name: dev-i-universe-xyz-app-1a-v1
  #   instanceType: m5a.xlarge
  #   availabilityZones: ["us-east-1a"]
  #   minSize: 1
  #   maxSize: 2
  #   privateNetworking: true
  #   ebsOptimized: true
  #   volumeEncrypted: true
  #   volumeSize: 64
  #   ssh:
  #     allow: false
  #   iam:
  #     withAddonPolicies:
  #       autoScaler: true
  #       externalDNS: true
  #       certManager: true
  #       cloudWatch: true
  #       ebs: true
  #   labels:
  #     digitalmob.ro/role: app
  #     digitalmob.ro/instance-type: general-purpose
  #     digitalmob.ro/pricing-tier: on-demand
  #     digitalmob.ro/workload-type: mixed
  # - name: dev-i-universe-xyz-app-1b-v1
  #   instanceType: m5a.xlarge
  #   availabilityZones: ["us-east-1b"]
  #   minSize: 1
  #   maxSize: 2
  #   privateNetworking: true
  #   ebsOptimized: true
  #   volumeEncrypted: true
  #   volumeSize: 64
  #   ssh:
  #     allow: false
  #   iam:
  #     withAddonPolicies:
  #       autoScaler: true
  #       externalDNS: true
  #       certManager: true
  #       cloudWatch: true
  #       ebs: true
  #   labels:
  #     digitalmob.ro/role: app
  #     digitalmob.ro/instance-type: general-purpose
  #     digitalmob.ro/pricing-tier: on-demand
  #     digitalmob.ro/workload-type: mixed
  - name: dev-i-universe-xyz-app-1a-v2
    instanceType: m5a.xlarge
    availabilityZones: ["us-east-1a"]
    minSize: 4
    maxSize: 5
    desiredCapacity: 4
    privateNetworking: true
    ebsOptimized: true
    volumeEncrypted: true
    volumeSize: 64
    ssh:
      allow: true
      publicKeyName: dev-eks-jump-host
      enableSsm: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true
        ebs: true
    labels:
      universe.xyz/role: app
      universe.xyz/instance-type: general-purpose
      universe.xyz/pricing-tier: on-demand
      universe.xyz/workload-type: mixed
  - name: dev-i-universe-xyz-app-1b-v2
    instanceType: m5a.xlarge
    availabilityZones: ["us-east-1b"]
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    privateNetworking: true
    ebsOptimized: true
    volumeEncrypted: true
    volumeSize: 64
    ssh:
      allow: true
      publicKeyName: dev-eks-jump-host
      enableSsm: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true
        ebs: true
    labels:
      universe.xyz/role: app
      universe.xyz/instance-type: general-purpose
      universe.xyz/pricing-tier: on-demand
      universe.xyz/workload-type: mixed